### ISSUE TITLE
PROJECT_DIR is it source code dir or binary directory

### ISSUE THREAD

**Issue by nagkumar** [whitesource/log4j-detect-distribution#1]
Can you pl. clarify if PROJECT_DIR  is a binary install directory in readme, 

I am hoping it would support both :) i.e. static code analysis and also jar dependencies scan

**Comment by annarozin** [comment]
Hi @nagkumar the readme file was updated with the following "The folder can include source code that uses maven/gradle in the project, as well as binaries (i.e jar files)"
