### ISSUE TITLE
Windows 10 access denied

### ISSUE THREAD

**Issue by repairmant** [whitesource/log4j-detect-distribution#7]
running with CMD as Admin
log4j-detect.exe scan

I get 14 errors saying:
fsWalkErrorFunc error: open C:\........ : Access is denied

**Comment by nabeelsaabna** [comment]
Hi @repairmant, the provided information does not help identify/understand the root cause.
with that said, the error is coming from the library in use: `github.com/karrick/godirwalk v1.16.1`

**Comment by repairmant** [comment]
Scanning C:\ for vulnerabilities...
fsWalkErrorFunc error:  open C:\Program Files\Windows Defender Advanced Threat Protection\Classification\Configuration: Access is denied.
fsWalkErrorFunc error:  open C:\ProgramData\Microsoft\Windows\SystemData: Access is denied.
fsWalkErrorFunc error:  open C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Cache: Access is denied.
fsWalkErrorFunc error:  open C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Cyber: Access is denied.
fsWalkErrorFunc error:  open C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\DataCollection: Access is denied.
fsWalkErrorFunc error:  open C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Downloads: Access is denied.
fsWalkErrorFunc error:  open C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\SenseCM: Access is denied.
fsWalkErrorFunc error:  open C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Temp\PSScriptOutputs: Access is denied.
fsWalkErrorFunc error:  open C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Trace: Access is denied.
fsWalkErrorFunc error:  open C:\ProgramData\Packages\Microsoft.SkypeApp_kzf8qxf38zg5c\S-1-5-21-3144404037-666759590-3269391922-1001\SystemAppData\Helium\Cache: Access is denied.
fsWalkErrorFunc error:  open C:\System Volume Information: Access is denied.
fsWalkErrorFunc error:  open C:\Windows\CSC: Access is denied.
fsWalkErrorFunc error:  open C:\Windows\ServiceProfiles\LocalService\AppData\Local\Microsoft\Ngc: Access is denied.
fsWalkErrorFunc error:  open C:\Windows\System32\LogFiles\WMI\RtBackup: Access is denied.

**Comment by JawadHalabiMTB** [comment]
@repairmant I think you are trying to scan directory which has a lot of system protected files, in this case it is expected to have permissions issues. at the end you need to use this tool in an appropriate way which is scan your own project folder instead.

hope it helps

**Comment by repairmant** [comment]
Didnt read the description and see that its for project not the whole PC.

Thanks
